### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by viktorpenelski** [sphinx-contrib/googleanalytics#11]
Hi, and thank you for working on this!

I was wondering if you have considered adding an open-source license to this repo?

As far as I can tell, the project currently has no license, which by default is equivalent to an [exclusive, no-permission license](https://choosealicense.com/no-permission/).

**Comment by jelmer** [comment]
The license is BSD, and is mentioned in the python metadata (setup.cfg).

**Comment by viktorpenelski** [comment]
Sorry for missing that 😅

Would it be OK if I open a PR to also add it as LICENSE.md to show in the github listing?

Edit: Anyway, opened a PR, I can just close it if you don't think it's a good idea

**Comment by jelmer** [comment]
On Tue, May 16, 2023 at 08:36:51PM -0700, Viktor Penelski wrote:
> Sorry for missing that 😅
> 
> Would it be OK if I open a PR to also add it as LICENSE.md to show in the github listing?

Yeah, that sounds great - thanks!
