### ISSUE TITLE
it doesn't work??

### ISSUE THREAD

**Issue by germa89** [sphinx-contrib/googleanalytics#9]
I am trying to use this extension in one of the project I work on.

The implementation is in here: https://github.com/pyansys/pymapdl/blob/4b66721e5778b978104820b802461f046d99cd47/doc/source/conf.py#L163-L164

The website with the tags is here: https://mapdl.docs.pyansys.com/dev/ 

I checked and the tag is correctly injected in the different pages:
![image](https://user-images.githubusercontent.com/28149841/210558602-1db9877a-8332-4e24-b78a-f01aead6063f.png)

**Comment by jelmer** [comment]
What about it doesn't work? I see a request to google-analytics.com when visiting that page.

**Comment by germa89** [comment]
How do you see the request?? Or you mean the code I share the screenshot?

**Comment by germa89** [comment]
![image](https://user-images.githubusercontent.com/28149841/210635290-eef46d26-ca35-4291-b10b-a1dc784d5c26.png)

**Comment by germa89** [comment]
PR where I merged:

https://github.com/pyansys/pymapdl/pull/1740

**Comment by jelmer** [comment]
Watching HTTP requests with my browser.

How does the code generated differ from the code suggested by analytics itself?

**Comment by germa89** [comment]
I think it is the same.

## Analytics suggestion:

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JQJKPV6ZVB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JQJKPV6ZVB');
</script>
```

## Implemented
```html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="generator" content="Docutils 0.19: https://docutils.sourceforge.io/">

    <!-- Google tag (gtag.js) -->
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-JQJKPV6ZVB"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-JQJKPV6ZVB');
    </script>
    
    <title>PyMAPDL documentation 0.64.dev0 — PyMAPDL</title>
    
<script>
  document.documentElement.dataset.mode = localStorage.getItem("mode") || "";
  document.documentElement.dataset.theme = localStorage.getItem("theme") || "light"
</script>
```

**Comment by jelmer** [comment]
Those look the same to me. Does it work with the analytics suggestion?

**Comment by germa89** [comment]
I just received some data.. it seems it just took a long time.... Thank you!
